"""Adicionando campos de CNPJ e telefone à tabela de usuários

Revision ID: 60d59b7d0386
Revises: b63d1005a5c5
Create Date: 2025-01-26 19:47:47.547176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d59b7d0386'
down_revision = 'b63d1005a5c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=18), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['cnpj'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('company_name')
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###
