-- UPDATE DA TABELA USERS --ALTER TABLE public."user"
ALTER TABLE public."user"
ADD COLUMN email VARCHAR(255) UNIQUE,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN role VARCHAR(50) DEFAULT 'user';




